In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
lab_en=LabelEncoder()
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
gauss=GaussianNB()
multi=MultinomialNB()
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
salary_data=pd.read_csv("SalaryData_Train.csv")
salary_data

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [3]:
salary_data.shape

(30161, 14)

In [4]:
salary_data.dtypes

age               int64
workclass        object
education        object
educationno       int64
maritalstatus    object
occupation       object
relationship     object
race             object
sex              object
capitalgain       int64
capitalloss       int64
hoursperweek      int64
native           object
Salary           object
dtype: object

In [5]:
salary_data.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [6]:
salary_data["workclass"]=lab_en.fit_transform(salary_data["workclass"])
salary_data["education"]=lab_en.fit_transform(salary_data["education"])
salary_data["maritalstatus"]=lab_en.fit_transform(salary_data["maritalstatus"])
salary_data["occupation"]=lab_en.fit_transform(salary_data["occupation"])
salary_data["relationship"]=lab_en.fit_transform(salary_data["relationship"])
salary_data["race"]=lab_en.fit_transform(salary_data["race"])
salary_data["sex"]=lab_en.fit_transform(salary_data["sex"])
salary_data["native"]=lab_en.fit_transform(salary_data["native"])
salary_data["Salary"]=lab_en.fit_transform(salary_data["Salary"])


In [7]:
salary_data.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   39          5          9           13              4           0   
1   50          4          9           13              2           3   
2   38          2         11            9              0           5   
3   53          2          1            7              2           5   
4   28          2          9           13              2           9   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             1     4    1         2174            0            40      37   
1             0     4    1            0            0            13      37   
2             1     4    1            0            0            40      37   
3             0     2    1            0            0            40      37   
4             5     2    0            0            0            40       4   

   Salary  
0       0  
1       0  
2       0  
3       0  
4       0

In [8]:
X=salary_data.drop(labels="Salary",axis=1)
y=salary_data[['Salary']]

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=12,)

In [12]:
y_pred_gtest=gauss.fit(X_train,y_train).predict(X_test)
y_pred_mtest=multi.fit(X_train,y_train).predict(X_test)

### Test for Gaussian 

In [13]:
accuracy_score(y_test,y_pred_gtest)

0.792971987402619

In [14]:
confusion_matrix(y_test,y_pred_gtest)

array([[4311,  246],
       [1003,  473]], dtype=int64)

### Test for multinomial

In [15]:
accuracy_score(y_test,y_pred_mtest)

0.7720868556273828

In [16]:
confusion_matrix(y_test,y_pred_mtest)

array([[4358,  199],
       [1176,  300]], dtype=int64)

### ---------------------------

### Test Data

In [17]:
test_data=pd.read_csv('SalaryData_Test.csv')
test_data.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [18]:
test_data["workclass"]=lab_en.fit_transform(test_data["workclass"])
test_data["education"]=lab_en.fit_transform(test_data["education"])
test_data["maritalstatus"]=lab_en.fit_transform(test_data["maritalstatus"])
test_data["occupation"]=lab_en.fit_transform(test_data["occupation"])
test_data["relationship"]=lab_en.fit_transform(test_data["relationship"])
test_data["race"]=lab_en.fit_transform(test_data["race"])
test_data["sex"]=lab_en.fit_transform(test_data["sex"])
test_data["native"]=lab_en.fit_transform(test_data["native"])
test_data["Salary"]=lab_en.fit_transform(test_data["Salary"])


In [19]:
test_data

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            40   
1                 0     4    1            0            0            50   
2                 0     4    1            0            0            40   
3                 0     2    1         7688            0            40   
4                 1     4    1            0            0            30   
...             ...   ...  ...          ...          ...           ...   
15055             3     4    1            0            0            40   
15056             1     4    0            0            0            36   
15057             0     4    1            0            0            50   
15058             3     1    1         5455            0            40   
15059             0     4    1            0            0            60   

       native  Salary  
0          37       0  
1          37       0  
2          37       1  
3          37       1  
4          37       0  
...       ...     ...  
15055      37       0  
15056      37       0  
15057      37       0  
15058      37       0  
15059      37       1  

[15060 rows x 14 columns]

In [20]:
xx=test_data.drop(labels=['Salary'],axis=1)
y=test_data[["Salary"]]

In [21]:
xx

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 3     2    1            0            0            40      37  
1                 0     4    1            0            0            50      37  
2                 0     4    1            0            0            40      37  
3                 0     2    1         7688            0            40      37  
4                 1     4    1            0            0            30      37  
...             ...   ...  ...          ...          ...           ...     ...  
15055             3     4    1            0            0            40      37  
15056             1     4    0            0            0            36      37  
15057             0     4    1            0            0            50      37  
15058             3     1    1         5455            0            40      37  
15059             0     4    1            0            0            60      37  

[15060 rows x 13 columns]

### Test for Gaussian 

In [22]:
pred=gauss.predict(xx)
pred1=multi.predict(xx)

In [25]:
accuracy_score(y,pred)

0.7943559096945552

In [27]:
confusion_matrix(y,pred)

array([[10755,   605],
       [ 2492,  1208]], dtype=int64)

### Test for multinomial

In [28]:
accuracy_score(y,pred1)

0.7749667994687915

In [29]:
confusion_matrix(y,pred1)

array([[10891,   469],
       [ 2920,   780]], dtype=int64)